services:
  web:
    build:
      context: https://github.com/SzymonEls/AI-productivity-app.git#main
    restart: unless-stopped
    user: "0:0"
    environment:
      FLASK_ENV: production
      SKIP_DB_BOOTSTRAP: "1"
      DATABASE_URL: sqlite:////app/instance/app.db
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./app/instance:/app/instance
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    driver: bridge
    external: true
