#!/bin/sh
set -eu

export SKIP_DB_BOOTSTRAP="${SKIP_DB_BOOTSTRAP:-1}"
INSTANCE_PATH="${INSTANCE_PATH:-/instance}"
ENV_FILE="$INSTANCE_PATH/.env"

mkdir -p "$INSTANCE_PATH"

if [ "$(id -u)" = "0" ]; then
    chown -R appuser:appuser "$INSTANCE_PATH"
fi

if [ ! -f "$ENV_FILE" ]; then
    SECRET_KEY="${SECRET_KEY:-$(python -c 'import secrets; print(secrets.token_urlsafe(48))')}"
    DATABASE_URL="${DATABASE_URL:-sqlite:///$INSTANCE_PATH/app.db}"
    REGISTRATION_ENABLED="${REGISTRATION_ENABLED:-true}"
    CALENDAR_TIMEZONE="${CALENDAR_TIMEZONE:-Europe/Warsaw}"
    OPENAI_API_KEY="${OPENAI_API_KEY:-}"
    OPENAI_MODEL="${OPENAI_MODEL:-gpt-4.1-mini}"
    OPENAI_TIMEOUT="${OPENAI_TIMEOUT:-30}"
    OPENAI_PROJECT_TIMEOUT="${OPENAI_PROJECT_TIMEOUT:-90}"
    OPENAI_TEMPERATURE="${OPENAI_TEMPERATURE:-0.7}"
    OPENAI_PROJECT_TEMPERATURE="${OPENAI_PROJECT_TEMPERATURE:-0.5}"

    cat > "$ENV_FILE" <<EOF
SECRET_KEY=${SECRET_KEY}
DATABASE_URL=${DATABASE_URL}
REGISTRATION_ENABLED=${REGISTRATION_ENABLED}
CALENDAR_TIMEZONE=${CALENDAR_TIMEZONE}
OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_MODEL=${OPENAI_MODEL}
OPENAI_TIMEOUT=${OPENAI_TIMEOUT}
OPENAI_PROJECT_TIMEOUT=${OPENAI_PROJECT_TIMEOUT}
OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
OPENAI_PROJECT_TEMPERATURE=${OPENAI_PROJECT_TEMPERATURE}
EOF
    if [ "$(id -u)" = "0" ]; then
        chown appuser:appuser "$ENV_FILE"
    fi
fi

if [ "$(id -u)" = "0" ]; then
    gosu appuser flask --app run.py db upgrade
    exec gosu appuser "$@"
fi

flask --app run.py db upgrade
exec "$@"
