/**
 * The time port, checked against values the Python it replaces produced.
 *
 * The golden file was generated by running app/time_tracking/service.py's own
 * arithmetic, so these are not assumptions about what the rules should be -
 * they are what the application has been doing.
 */

import { describe, expect, it, beforeAll } from "vitest";

import golden from "./__golden__time.json";
import {
  dayBounds,
  formatDuration,
  lastSessionLabel,
  overlapSeconds,
  useTimezone,
  firstPlanSectionTitle,
  entriesForRange,
  dailyTotalsByProject,
} from "./time";
import type { TimeEntry } from "../sync/types";

beforeAll(() => useTimezone("Europe/Warsaw"));

function entry(over: Partial<TimeEntry> = {}): TimeEntry {
  return {
    uid: "u1",
    rev: 1,
    updated_at: "2026-01-15T00:00:00Z",
    started_at: "2026-01-15T09:00:00Z",
    ended_at: "2026-01-15T10:00:00Z",
    description: null,
    project_title_snapshot: null,
    project_uid: "p1",
    ...over,
  };
}

describe("formatDuration", () => {
  it("matches the Python output for every sampled value", () => {
    for (const [seconds, expected] of Object.entries(golden.durations)) {
      expect(formatDuration(Number(seconds)), `for ${seconds}s`).toBe(expected);
    }
  });
});

describe("lastSessionLabel", () => {
  it("crosses every threshold where Python crosses it", () => {
    const now = new Date("2026-06-01T12:00:00Z");
    for (const [seconds, expected] of Object.entries(golden.lastSession)) {
      const then = new Date(now.getTime() - Number(seconds) * 1000).toISOString();
      expect(lastSessionLabel(then, now), `for ${seconds}s ago`).toBe(expected);
    }
  });

  it("says none when there is no session", () => {
    expect(lastSessionLabel(null)).toBe("Last session: none");
  });
});

describe("dayBounds", () => {
  it("puts a local day on the right UTC instants, clock changes included", () => {
    for (const [day, [start, end]] of Object.entries(golden.dayBounds)) {
      const [gotStart, gotEnd] = dayBounds(day);
      expect(gotStart.getTime(), `${day} start`).toBe(new Date(start).getTime());
      // Python's time.max carries microseconds; milliseconds is as close as
      // JavaScript gets, and the difference cannot move a session.
      expect(Math.abs(gotEnd.getTime() - new Date(end).getTime()), `${day} end`)
        .toBeLessThanOrEqual(1);
    }
  });
});

describe("overlapSeconds", () => {
  it("splits a timer left running across midnight, as Python does", () => {
    const running = entry({
      started_at: golden.midnightEntry.started_at,
      ended_at: golden.midnightEntry.ended_at,
    });
    for (const [day, expected] of Object.entries(golden.midnightEntry.overlap)) {
      const [start, end] = dayBounds(day);
      expect(overlapSeconds(running, start, end), day).toBe(expected);
    }
  });

  it("counts an unfinished timer up to now, not beyond", () => {
    const now = new Date("2026-01-15T09:30:00Z");
    const running = entry({ started_at: "2026-01-15T09:00:00Z", ended_at: null });
    const [start, end] = dayBounds("2026-01-15");
    expect(overlapSeconds(running, start, end, now)).toBe(1800);
  });
});

describe("entriesForRange", () => {
  it("keeps what touches the window and drops what does not", () => {
    const [start, end] = dayBounds("2026-01-15");
    const inside = entry({ uid: "in" });
    const before = entry({
      uid: "before",
      started_at: "2026-01-10T09:00:00Z",
      ended_at: "2026-01-10T10:00:00Z",
    });
    const kept = entriesForRange([inside, before], start, end).map((e) => e.uid);
    expect(kept).toEqual(["in"]);
  });

  it("keeps a still-running entry that started before the window", () => {
    const [start, end] = dayBounds("2026-01-16");
    const running = entry({ uid: "run", started_at: "2026-01-15T09:00:00Z", ended_at: null });
    expect(entriesForRange([running], start, end).map((e) => e.uid)).toEqual(["run"]);
  });
});

describe("dailyTotalsByProject", () => {
  it("adds up per project", () => {
    const totals = dailyTotalsByProject(
      [
        entry({ uid: "a", project_uid: "p1" }),
        entry({
          uid: "b",
          project_uid: "p1",
          started_at: "2026-01-15T12:00:00Z",
          ended_at: "2026-01-15T12:30:00Z",
        }),
        entry({
          uid: "c",
          project_uid: "p2",
          started_at: "2026-01-15T14:00:00Z",
          ended_at: "2026-01-15T14:15:00Z",
        }),
      ],
      "2026-01-15"
    );
    expect(totals.get("p1")).toBe(3600 + 1800);
    expect(totals.get("p2")).toBe(900);
  });
});

describe("firstPlanSectionTitle", () => {
  it("takes the first top-level heading only", () => {
    expect(firstPlanSectionTitle("# One\n\n## Two\n\n# Three")).toBe("One");
    expect(firstPlanSectionTitle("no heading here")).toBe("");
    expect(firstPlanSectionTitle("#  \n# Real")).toBe("Real");
    expect(firstPlanSectionTitle(null)).toBe("");
  });
});
